ces:  
  jenkinsToken:           '71063193-ee67-4b52-890a-58843f33c183'
  token:                  '665fc9fb-39de-428a-8a67-a3619752873d'
hci:  
  connectionId:           '196de681-04d7-4170-824f-09a5457c5cda'
  hostToken:              'ea48408b-b2be-4810-8f4e-5b5f35977eb1'
ispw:
  localFolder:            'MF_Source'
  url:                    'http://cwcc.compuware.com:2020'
  runtime:                'ispw'
ttt:
  ftServerUrl:            'http://cwcc.compuware.com:2020/totaltestapi/'
  utFolder:               'tests'
  gitBranch:              'master'
  ftEnvironment:          '5b508b8a787be73b59238d38'
  cocoRepository:         'HDDRXM0.DEMO.COCO.REPOS'
git:
  server:                 'https://github.com'
  project:                'ralphnuessecpwr'
  credentials:            '67a3fb18-073f-498b-adee-1a3c75192745'
sonar:
  scannerName:            'scanner'
  serverHost:             'localhost'
  serverUrl:              'http://sonarqube.nasa.cpwr.corp:9000'
  httpRequestAuthHeader:  ''
xlr:
  template:               'A Release from Jenkins - RNU'
  user:                   'admin'